### ISSUE TITLE
Feature Request: Ability to choose measurement system (Metric to Imperial)

### ISSUE THREAD

**Issue by KillerGryphon** [Zakarik/foundry-mm3#54]
Hello there! Thanks firstly for all the work you have done, I just wanted to bring up something me and my players found a tad bit annoying. In the M&M 3rd Edition Handbook, and in Hero Labs, all measurements (including the measurement table) are in the Imperial system. Superiority of either system aside, it's a pain when my players and I have the chart in an entirely different measurement system, but the in-game Speeds are all Metric. It would be amazing for all of us to have a standardized system, so I humbly ask, may you please add an option to swap to the Imperial system for the Speed and such?

**Comment by DeviousHearts** [comment]
Go to 'Configure Settings" under "Mutants and Masterminds 3E" go down to the 4th item down which is "Measuring System" and switch to "Imperial"

**Comment by DeviousHearts** [comment]
And in the French version of M&M, the system is, of course, in French and since the master coder Zakarik is French, it is in Metric but one of my first few requests to him was for the Imperial system for us Americans.... until we, or course, catch up with the rest f the civilized world and convert to metric. 🙂
