### ISSUE TITLE
Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.

### ISSUE THREAD

**Issue by Niklasbor** [Zakarik/foundry-mm3#8]
When attempting to create or load a scene, progress stops at 68%, and the following message is logged 11 times the console
```Uncaught Error: The SVG image must have width and height defined (in pixels), canvas API needs them.```

**Comment by Zakarik** [comment]
I don't have any problems of my own.
Which version of Foundry?
Can you send me your world, so I can give it a try?
Have you checked without a module?

**Comment by GrieverShockwavePulsar** [comment]
Same issue as:  https://github.com/Zakarik/token-action-hud-mm3/issues/2

**Comment by Niklasbor** [comment]
As mentioned in the other issue, this appears to be specific to Firefox

**Comment by Zakarik** [comment]
So I have a problem.
I've found potential indications of how to solve the problem, but I have no way of testing its resolution, because on my side, under Firefox (same version), I don't have this problem.

Can one of you contact me on Discord, at a time when you have time, so that we can try it out (in writing)?

**Comment by Zakarik** [comment]
Should be corrected in the update just released.

**Comment by GrieverShockwavePulsar** [comment]
Confirmed working in Firefox.
